apiVersion: apps/v1
kind: Deployment
metadata:
  name: taina-backend
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: taina-backend
  template:
    spec:
      containers:
        - name: taina-backend
          image: fake-image
          resources:
            requests:
              memory: 128Mi
              cpu: 0.1
            limits:
              memory: 256Mi
              cpu: 0.5
          ports:
            - containerPort: 80
              name: http
          envFrom:
          - configMapRef:
              name: taina-backend-config
          # Uncomment the secretRef block below if your Playground application has secrets
          # See the README for instructions on how to create secrets
          #- secretRef:
          #    name: taina-backend-secrets
          readinessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
